
function envelope_generator_config(this_block)

  % Revision History:
  %
  %   02-Jul-2025  (17:41 hours):
  %     Original code was machine generated by Vitis Model Composer after parsing
  %     C:\Users\fsydere\Workspace\IFM\IFM_RTL\IFM_RTL.srcs\sources_1\new\envelope_generator.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('envelope_generator');

  % Vitis Model Composer has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('clk');
  this_block.addSimulinkInport('real_part');
  this_block.addSimulinkInport('imag_part');
  this_block.addSimulinkInport('data_valid');

  this_block.addSimulinkOutport('real_part_delayed');
  this_block.addSimulinkOutport('imag_part_delayed');
  this_block.addSimulinkOutport('data_valid_delayed');
  this_block.addSimulinkOutport('envelope');

  real_part_delayed_port = this_block.port('real_part_delayed');
  real_part_delayed_port.setType('UFix_16_0');

  imag_part_delayed_port = this_block.port('imag_part_delayed');
  imag_part_delayed_port.setType('UFix_16_0');

  data_valid_delayed_port = this_block.port('data_valid_delayed');
  data_valid_delayed_port.setType('UFix_1_0');
  data_valid_delayed_port.useHDLVector(false);

  envelope_port = this_block.port('envelope');
  envelope_port.setType('UFix_1_0');
  envelope_port.useHDLVector(false);


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('clk').width ~= 1)
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

    if (this_block.port('real_part').width ~= 16)
      this_block.setError('Input data type for port "real_part" must have width=16.');
    end

    if (this_block.port('imag_part').width ~= 16)
      this_block.setError('Input data type for port "imag_part" must have width=16.');
    end

    if (this_block.port('data_valid').width ~= 1)
      this_block.setError('Input data type for port "data_valid" must have width=1.');
    end

    this_block.port('data_valid').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % Vitis Model Composer found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../IFM_RTL/IFM_RTL.srcs/sources_1/new/envelope_generator.v');

return;


% This function converts the matlab array to VHDL array Style 
% and this is valid only in case of generic parameters. 
function arrayHDLType = convertArrayType(inArr) 
arrayHDLType = '';
for i=1:length(inArr)
    if (i == 1)
        arrayHDLType = [arrayHDLType '(' num2str(inArr(i))]; 
    elseif (i == length(inArr)) 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i)) ')']; 
    else 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i))]; 
    end 
end 
