# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.srcs/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/IFM_bd_IFM_1_0.xci
# IP: The module: 'IFM_bd_IFM_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_c_counter_binary_v12_0_i0/ifm_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==ifm_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_c_counter_binary_v12_0_i1/ifm_c_counter_binary_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==ifm_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_cmpy_v6_0_i0/ifm_cmpy_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_cmpy_v6_0_i0 || ORIG_REF_NAME==ifm_cmpy_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_cordic_v6_0_i0/ifm_cordic_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_cordic_v6_0_i0 || ORIG_REF_NAME==ifm_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_div_gen_v5_1_i0/ifm_div_gen_v5_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_div_gen_v5_1_i0 || ORIG_REF_NAME==ifm_div_gen_v5_1_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_div_gen_v5_1_i1/ifm_div_gen_v5_1_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_div_gen_v5_1_i1 || ORIG_REF_NAME==ifm_div_gen_v5_1_i1} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_mult_gen_v12_0_i0/ifm_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_mult_gen_v12_0_i0 || ORIG_REF_NAME==ifm_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_mult_gen_v12_0_i1/ifm_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_mult_gen_v12_0_i1 || ORIG_REF_NAME==ifm_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_mult_gen_v12_0_i2/ifm_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_mult_gen_v12_0_i2 || ORIG_REF_NAME==ifm_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/constrs/ifm.xdc
# XDC: The top module name and the constraint reference have the same name: 'IFM_bd_IFM_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.srcs/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/IFM_bd_IFM_1_0.xci
# IP: The module: 'IFM_bd_IFM_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_c_counter_binary_v12_0_i0/ifm_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==ifm_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_c_counter_binary_v12_0_i1/ifm_c_counter_binary_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==ifm_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_cmpy_v6_0_i0/ifm_cmpy_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_cmpy_v6_0_i0 || ORIG_REF_NAME==ifm_cmpy_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_cordic_v6_0_i0/ifm_cordic_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_cordic_v6_0_i0 || ORIG_REF_NAME==ifm_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_div_gen_v5_1_i0/ifm_div_gen_v5_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_div_gen_v5_1_i0 || ORIG_REF_NAME==ifm_div_gen_v5_1_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_div_gen_v5_1_i1/ifm_div_gen_v5_1_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_div_gen_v5_1_i1 || ORIG_REF_NAME==ifm_div_gen_v5_1_i1} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_mult_gen_v12_0_i0/ifm_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_mult_gen_v12_0_i0 || ORIG_REF_NAME==ifm_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_mult_gen_v12_0_i1/ifm_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_mult_gen_v12_0_i1 || ORIG_REF_NAME==ifm_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/ifm_mult_gen_v12_0_i2/ifm_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ifm_mult_gen_v12_0_i2 || ORIG_REF_NAME==ifm_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/fsydere/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/ip/IFM_bd_IFM_1_0/constrs/ifm.xdc
# XDC: The top module name and the constraint reference have the same name: 'IFM_bd_IFM_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
