# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/ifm_clock.xdc

# XDC: imports/sysgen/ifm.xdc

# Block Designs: bd/IFM_bd/IFM_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IFM_bd || ORIG_REF_NAME==IFM_bd} -quiet] -quiet

# IP: bd/IFM_bd/ip/IFM_bd_IFM_1_0/IFM_bd_IFM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IFM_bd_IFM_1_0 || ORIG_REF_NAME==IFM_bd_IFM_1_0} -quiet] -quiet

# XDC: c:/Users/fsyde/Workspace/IFM/Model_Composer/netlist/ip/IFM/src/ip_catalog/ifm.gen/sources_1/bd/IFM_bd/IFM_bd_ooc.xdc
